rootProject.name = 'PaperMC-Plugin-Collection'

def pluginsRoot = 'papermc_plugins'

[
    'adminchat',
    'automessages',
    'bigbrother',
    'gamemodemanager',
    'noctiview',
    'perkmenu',
    'vaculoot'
].each { name ->
    include(":${name}")
    project(":${name}").projectDir = file("${pluginsRoot}/${name}")
}